import localFont from "next/font/local";
import "./globals.css";

const gabaritoFont = localFont({
  src: "./fonts/GabaritoVF.ttf",
  display: "swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gabaritoFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
